{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# asyncio私房手册"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "目录和官方文档一致，主要补充学习官方文档中的一些心得和细节。\n",
    "- [官方文档](https://docs.python.org/zh-cn/3/library/asyncio.html)\n",
    "- [Guide to Concurrency in Python with Asyncio](https://www.integralist.co.uk/posts/python-asyncio/)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 高级API"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### task"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "`create_task`运行的时间非常微妙，先看代码：\n",
    "```python\n",
    "async def func1():\n",
    "    print(\"func1 start!\", time.strftime(\"%X\"))\n",
    "    await asyncio.sleep(1)\n",
    "    print(\"func1 end!\", time.strftime(\"%X\"))\n",
    "\n",
    "\n",
    "async def func2():\n",
    "    print(\"func2 start!\", time.strftime(\"%X\"))\n",
    "    await asyncio.sleep(2)\n",
    "    print(\"func2 end!\", time.strftime(\"%X\"))\n",
    "\n",
    "\n",
    "async def main():\n",
    "    task1 = asyncio.create_task(func1())  # 任务被放入事件循环，但未运行\n",
    "    task2 = asyncio.create_task(func2())  # 任务被放入事件循环，但未运行\n",
    "    print(\"main start!\")\n",
    "    await task1  # 主程序挂起，开始事件循环，执行任务\n",
    "    await task2\n",
    "    print(\"main end!\")\n",
    "\n",
    "\n",
    "asyncio.run(main())\n",
    "```\n",
    "输出为：\n",
    "```\n",
    "main start!\n",
    "func1 start! 09:07:25\n",
    "func2 start! 09:07:25\n",
    "func1 end! 09:07:26\n",
    "func2 end! 09:07:27\n",
    "main end!\n",
    "```\n",
    "可见，协程并非是在`create_task`的时候就开始运行。task运行的时间非常微妙，`create_task`创建了一个任务，并将其放入后台的事件循环队列中，然后马上回到主程序，但是此时并没有运行，直到遇到紧接着的`await`，即主程序被挂起，开始执行事件循环里的事件，此时任务开始运行。\n",
    "\n",
    "把`main`改一改，可以看得更清晰。\n",
    "```python\n",
    "async def main():\n",
    "    task1 = asyncio.create_task(func1())\n",
    "    task2 = asyncio.create_task(func2())\n",
    "    await asyncio.sleep(.1)\n",
    "    print(\"main start!\")\n",
    "    print(\"main end!\")\n",
    "```\n",
    "输出为：\n",
    "```\n",
    "func1 start! 09:29:57\n",
    "func2 start! 09:29:57\n",
    "main start!\n",
    "main end!\n",
    "```\n",
    "可见，即使没有`await task1`，任务也会运行，因为任务前面已经被加入到事件循环队列，当遇到`await asyncio.sleep`时，主程序挂起，运行事件循环里的任务，遇到任务中的`await`时，又回到主程序。此时没有`await task1`这样的语句来获取任务结果，因此直接就结束了。"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### gather"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "gather可以将协程包装成任务加入事件循环队列，也就是使用gather，可以直接传入协程而不需要先创建任务，gather的异常处理有点微妙：\n",
    "```python\n",
    "async def func1():\n",
    "    print(\"func1 start!\", time.strftime(\"%X\"))\n",
    "    raise RuntimeError(\"func1 failed!\")\n",
    "    await asyncio.sleep(1)\n",
    "    print(\"func1 end!\", time.strftime(\"%X\"))\n",
    "    return \"func1\"\n",
    "\n",
    "\n",
    "async def func2():\n",
    "    print(\"func2 start!\", time.strftime(\"%X\"))\n",
    "    await asyncio.sleep(2)\n",
    "    print(\"func2 end!\", time.strftime(\"%X\"))\n",
    "    return \"func2\"\n",
    "\n",
    "\n",
    "async def main():\n",
    "    print(\"main start!\", time.strftime(\"%X\"))\n",
    "    try:\n",
    "        results = await asyncio.gather(func1(), func2())  # 异常抛出\n",
    "        print(\"results is\", results)\n",
    "    except RuntimeError as e:\n",
    "        print(e)\n",
    "        await asyncio.sleep(3)  # 如果继续等待，则可以看到func2仍然运行了\n",
    "    print(\"main end!\", time.strftime(\"%X\"))\n",
    "\n",
    "\n",
    "asyncio.run(main())\n",
    "```\n",
    "输出为：\n",
    "```\n",
    "main start! 10:01:01\n",
    "func1 start! 10:01:01\n",
    "func2 start! 10:01:01\n",
    "func1 failed!\n",
    "func2 end! 10:01:03\n",
    "main end! 10:01:04\n",
    "```\n",
    "默认情况下，如果任务队列里的任务抛出错误，会向上传播，要注意的是，队列里的其它任务不会取消还是会继续运行，如果设置`return_exception=True`，则异常不会抛出，会和结果一起返回。如：\n",
    "```python\n",
    "async def main():\n",
    "    print(\"main start!\", time.strftime(\"%X\"))\n",
    "    results = await asyncio.gather(func1(), func2(), return_exceptions=True)\n",
    "    print(\"results is\", results)\n",
    "    print(\"main end!\", time.strftime(\"%X\"))\n",
    "```\n",
    "此时返回的结果是：\n",
    "```python\n",
    "main start! 10:08:52\n",
    "func1 start! 10:08:52\n",
    "func2 start! 10:08:52\n",
    "func2 end! 10:08:54\n",
    "results is [RuntimeError('func1 failed!'), 'func2']\n",
    "main end! 10:08:54\n",
    "```\n",
    "gather返回一个future，可以在这个future上调用cancel，但是它的一些细节还是没有弄清楚，以下记录了stack overflow的一些问题：\n",
    "- [How to cancel all remaining tasks in gather if one fails?](https://stackoverflow.com/questions/59073556/how-to-cancel-all-remaining-tasks-in-gather-if-one-fails)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### wait"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "`wait`和`gather`有点类似，都是获取任务结果的方法，不过`wait`比`gather`更灵活：\n",
    "```python\n",
    "async def main():\n",
    "    print(\"main start!\", time.strftime(\"%X\"))\n",
    "    done, pending = await asyncio.wait([func1(), func2()], timeout=2)\n",
    "    print(done.pop().result())\n",
    "    for p in pending:\n",
    "        p.cancel()\n",
    "    print(\"main end!\", time.strftime(\"%X\"))\n",
    "```\n",
    "输出为：\n",
    "```\n",
    "main start! 14:59:21\n",
    "func2 start! 14:59:21\n",
    "func1 start! 14:59:21\n",
    "func1 end! 14:59:22\n",
    "func1\n",
    "main end! 14:59:23\n",
    "```\n",
    "`wait`返回done和pending两个集合，分别包含已经完成的任务和被挂起的任务，可以通过`timeout`关键字设定等待时间，也可以通过`return_when`关键字设定返回的条件，比如`asyncio.FIRST_COMPLETED`，表示第一个就返回。"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### as_completed"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "也是用来获取结果，感觉和`gather`差不多，不过返回一个生成器，然后迭代生成器来获取结果，注意，其返回的结果是`Future`，并且必须调用`await`来等待`Future`的结果，否则会抛出错误：\n",
    "```python\n",
    "async def main():\n",
    "    print(\"main start!\", time.strftime(\"%X\"))\n",
    "    tasks = asyncio.as_completed([func1(), func2()])\n",
    "    for task in tasks:\n",
    "        print(await task)\n",
    "    print(\"main end!\", time.strftime(\"%X\"))\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### shield"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "shield不太好理解，它并不是真正的禁止任务被取消，可以把它理解为任务的一个状态，当使用`shield`包装一个协程，则会把这个协程包装为一个Future并且立即将其放入事件循环队列，当调用`Future.cancel()`方法的时候，`Future`会被标记成“取消”的状态，当`await`这个`Future`的时候，会立即抛出`CancelledError`的错误，但是实际上，这个Future依然在队列中，并未受影响：\n",
    "```python\n",
    "async def main():\n",
    "    print(\"main start!\", time.strftime(\"%X\"))\n",
    "    task1 = asyncio.create_task(func1())\n",
    "    task1_with_shield = asyncio.shield(task1) \n",
    "    try:\n",
    "        task1_with_shield.cancel()\n",
    "        await task1_with_shield  # 只要await task1_with_shield就会抛出CancelledError错误\n",
    "    except asyncio.CancelledError:\n",
    "        print(\"stask1 canceled!\")\n",
    "        await asyncio.sleep(2)  # 实际的task1仍然会运行，不受影响\n",
    "    print(\"main end!\", time.strftime(\"%X\"))\n",
    "```\n",
    "输出为：\n",
    "```\n",
    "main start! 14:18:21\n",
    "stask1 canceled!\n",
    "func1 start! 14:18:21\n",
    "func1 end! 14:18:22\n",
    "main end! 14:18:23\n",
    "```\n",
    "因此，可以在捕获了错误以后，仍然获取任务的值：\n",
    "```python\n",
    "async def main():\n",
    "    print(\"main start!\", time.strftime(\"%X\"))\n",
    "    task1 = asyncio.create_task(func1())\n",
    "    task1_with_shield = asyncio.shield(task1)\n",
    "    try:\n",
    "        task1_with_shield.cancel()\n",
    "        await task1_with_shield\n",
    "    except asyncio.CancelledError:\n",
    "        print(\"stask1 canceled!\")\n",
    "        r = await task1  # task1仍然在队列中运行，可以获取task1的返回值\n",
    "        print(r)\n",
    "    print(\"main end!\", time.strftime(\"%X\"))\n",
    "```\n",
    "输出为：\n",
    "```python\n",
    "main start! 14:30:42\n",
    "stask1 canceled!\n",
    "func1 start! 14:30:42\n",
    "func1 end! 14:30:43\n",
    "func1\n",
    "main end! 14:30:43\n",
    "```\n",
    "要注意的是，`shield`如果包装协程的话，不能像上面这样获取协程的值，比如：\n",
    "```python\n",
    "async def main():\n",
    "    print(\"main start!\", time.strftime(\"%X\"))\n",
    "    task1_with_shield = asyncio.shield(func1())\n",
    "    try:\n",
    "        task1_with_shield.cancel()\n",
    "        await task1_with_shield\n",
    "    except asyncio.CancelledError:\n",
    "        print(\"stask1 canceled!\")\n",
    "        r = await func1()  # 这里的func1()创建了一个新的协程，和task1_with_shield并非队列里的同一个任务\n",
    "        print(r)\n",
    "    print(\"main end!\", time.strftime(\"%X\"))\n",
    "```\n",
    "输出为：\n",
    "```\n",
    "main start! 14:33:15\n",
    "stask1 canceled!\n",
    "func1 start! 14:33:15\n",
    "func1 start! 14:33:15\n",
    "func1 end! 14:33:16\n",
    "func1\n",
    "main end! 14:33:16\n",
    "func1 end! 14:33:16\n",
    "```\n",
    "可见，func1执行了两次，这并不是想要的结果。"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### asyncio.run"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "`asyncio.run`基本上可以近似为以下的代码：\n",
    "```python\n",
    "import asyncio, sys, types\n",
    "\n",
    "def run(coro):\n",
    "    if sys.version_info >= (3, 7):\n",
    "        return asyncio.run(coro)\n",
    "\n",
    "    # Emulate asyncio.run() on older versions\n",
    "\n",
    "    # asyncio.run() requires a coroutine, so require it here as well\n",
    "    if not isinstance(coro, types.CoroutineType):\n",
    "        raise TypeError(\"run() requires a coroutine object\")\n",
    "\n",
    "    loop = asyncio.new_event_loop()\n",
    "    asyncio.set_event_loop(loop)\n",
    "    try:\n",
    "        return loop.run_until_complete(coro)\n",
    "    finally:\n",
    "        loop.close()\n",
    "        asyncio.set_event_loop(None)\n",
    "```\n",
    "因此，在使用它的时候，和直接通过loop调用有微妙的区别，来源于以下的代码，在屏幕上运行两个协程，一个会动态的显示`thinking!`，`thinking!`字符前面会有线条转动的动画，一个在2秒钟以后打印结果：\n",
    "```python\n",
    "import asyncio\n",
    "import itertools\n",
    "import sys\n",
    "\n",
    "\n",
    "async def spin(msg):\n",
    "    write, flush = sys.stdout.write, sys.stdout.flush\n",
    "    for char in itertools.cycle(\"|/-\\\\\"):\n",
    "        status = char + ' ' + msg\n",
    "        write(status)\n",
    "        flush()\n",
    "        write('\\x08' * len(status))\n",
    "        try:\n",
    "            await asyncio.sleep(.1)  # 调用spin.cancel的话，异常会在这里抛出\n",
    "        except asyncio.CancelledError:\n",
    "            break\n",
    "    write(' ' * len(status) + '\\x08' * len(status))\n",
    "\n",
    "\n",
    "async def slow_function():\n",
    "    await asyncio.sleep(2)\n",
    "    return 42\n",
    "\n",
    "\n",
    "async def supervisor():\n",
    "    spinner = asyncio.create_task(spin('thinking!'))\n",
    "    result = await slow_function()\n",
    "    spinner.cancel()\n",
    "    return result\n",
    "\n",
    "\n",
    "def main():\n",
    "    loop = asyncio.get_event_loop()\n",
    "    result = loop.run_until_complete(supervisor())\n",
    "    loop.close()\n",
    "    print(result)\n",
    "\n",
    "\n",
    "main() \n",
    "```\n",
    "最终输出为42，符合预期，而如果稍微修改一下main函数，使用`asyncio.run`运行，如下：\n",
    "```python\n",
    "async def main():\n",
    "    result = await supervisor()\n",
    "    print(result)\n",
    "\n",
    "asyncio.run(main())\n",
    "```\n",
    "此时，最终输出为`42thinking!`，问题出在哪里呢？因为两种方式`loop.close()`执行的时间点不同，第一种是先调用`loop.close`，再打印result，而第二种是先打印result，然后再调用`loop.close`。在`supervisor`中，在`spinner.cancel`处，并不会挂起，而是将spinner的状态设置为`cancel`，并返回`result`。当调用`loop.close`时，此时`spin`还在事件循环队列中，处于挂起状态，所以会继续执行`spin`。\n",
    "1. 第一种情况，相当于先`loop.close`，结束`spin`协程以后，再`print(result)`，相当于会先执行`write(' ' * len(status) + '\\x08' * len(status))`，将屏幕上的`thinking!`字符消除，最后打印结果。\n",
    "2. 第二种情况，相当于先打印result，然后再`loop.close`，执行`write(' ' * len(status) + '\\x08' * len(status))`，而由于`print(result)`导致了换行，所以最终结果为`42thinking!`，要解决的话也很简单，可以将`print(result)`改为`print(result, end='')`就行了。"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 低级API"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Future"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Future的概念并不是很好理解，它是一个低层级的API，做个类比，可以把它想象成一个放礼物的盒子，现在我们要送礼，但是事先并不知道送什么，我们可以先对这个盒子做一些装饰，然后在未来的某个时刻，再把礼物放进去，最终的目的是获取这个盒子里的礼物。在代码中，我们可以先创建一个`Future`，可以先为这个future添加回调函数（装饰盒子），再在后期设置future的结果（把礼物放进盒子），最终的目的是获取这个结果（得到礼物），比如：\n",
    "```python\n",
    "import asyncio\n",
    "\n",
    "\n",
    "async def set_future_result(future, delay, result):\n",
    "    await asyncio.sleep(delay)\n",
    "    future.set_result(42)\n",
    "\n",
    "\n",
    "def callback(future):\n",
    "    print(\"future is finished! result is\", future.result())\n",
    "\n",
    "\n",
    "async def main():\n",
    "    loop = asyncio.get_running_loop()\n",
    "    future = loop.create_future()\n",
    "    future.add_done_callback(callback)\n",
    "    loop.create_task(set_future_result(future, 2, 42))\n",
    "    await future\n",
    "\n",
    "\n",
    "asyncio.run(main())  # 输出为：future is finished! result is 42\n",
    "```\n",
    "注意，需要安排一个任务来设置future的结果，而不能在`add_done_callback()`回调函数里面设置，因为`future.set_result()`会同时将future的状态设置为`done`，而`add_done_callback`只有在future的状态为done时才会触发，因此如果在`add_done_callback()`设置future的结果，`await future`会导致程序挂死。"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### run_in_executor"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "`run_in_executor`可以新开一个线程或者一个进程来运行同步的函数，返回一个asyncio的future，这样就可以通过协程来并发的运行多个同步函数。比如有两个同步函数，一个是io阻塞型的，一个是计算密集型的，一般情况下，我们只能够同步的运行这两个函数，比如：\n",
    "```python\n",
    "def blocking_io():\n",
    "    print(time.strftime(\"%X\"), \"start blocking io\")\n",
    "    time.sleep(3)\n",
    "    return 42\n",
    "\n",
    "\n",
    "def cpu_bound():\n",
    "    print(time.strftime(\"%X\"), \"start cpu bound\")\n",
    "    return sum(i * i for i in range(10 ** 7))\n",
    "\n",
    "blocking_io_result = blocking_io()\n",
    "cpu_bound_result = cpu_bound()\n",
    "print(blocking_io_result, cpu_bound_result)\n",
    "```\n",
    "但是，现在我们为了提高性能，想要同时运行这两个函数，传统的做法比较麻烦（可以开两个线程，其中一个线程对cpu_bound做封装，在内部使用进程来运行cpu_bound），如果利用asyncio，则十分简单：\n",
    "```python\n",
    "import asyncio\n",
    "import concurrent.futures\n",
    "import time\n",
    "\n",
    "\n",
    "def blocking_io():\n",
    "    print(time.strftime(\"%X\"), \"start blocking io\")\n",
    "    time.sleep(2)\n",
    "    return 42\n",
    "\n",
    "\n",
    "def cpu_bound():\n",
    "    print(time.strftime(\"%X\"), \"start cpu bound\")\n",
    "    return sum(i * i for i in range(10 ** 7))\n",
    "\n",
    "\n",
    "async def async_blocking_io():\n",
    "    loop = asyncio.get_running_loop()\n",
    "    with concurrent.futures.ProcessPoolExecutor() as pool:\n",
    "        result = await loop.run_in_executor(pool, cpu_bound)\n",
    "        print(time.strftime(\"%X\"), \"blocking io result is\", result)\n",
    "\n",
    "\n",
    "async def async_cpu_bound():\n",
    "    loop = asyncio.get_running_loop()\n",
    "    with concurrent.futures.ThreadPoolExecutor() as pool:\n",
    "        result = await loop.run_in_executor(pool, blocking_io)\n",
    "        print(time.strftime(\"%X\"), \"cpu bound result is\", result)\n",
    "\n",
    "\n",
    "async def main():\n",
    "    await asyncio.gather(async_cpu_bound(), async_blocking_io())\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    asyncio.run(main())\n",
    "```\n",
    "输出结果如下：\n",
    "```\n",
    "16:53:25 start blocking io\n",
    "16:53:25 start cpu bound\n",
    "16:53:26 blocking io result is 333333283333335000000\n",
    "16:53:27 cpu bound result is 42\n",
    "```\n",
    "这里有一点要非常注意，就是创建新的进程会复制整个代码，所以调用的语句`asyncio.run(main())`必须放在`if __name__ == \"__main__\":`中，否则会抛出错误，而且抛出的错误说明并不直观，具体原因见《python那些事儿》笔记的multiprocessing模块一节。"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### asyncio.Future vs concurrent.futures.Future"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "`asyncio.Future`虽然和`concurrent.futures.Future`虽然有十分类似的API，但是两者其实是完全不同的。但是`concurrent.futures.Future`可以通过`asyncio.wrap_future`转换为`asyncio.Future`，其实在`run_in_executor`内部就是这么做的，也可以手动进行转换：\n",
    "```python\n",
    "import asyncio\n",
    "import random\n",
    "from concurrent.futures import ThreadPoolExecutor\n",
    "from time import sleep\n",
    "\n",
    "\n",
    "def return_after_5_secs(message):\n",
    "    sleep(5)\n",
    "    return message\n",
    "\n",
    "\n",
    "pool = ThreadPoolExecutor(3)\n",
    "\n",
    "\n",
    "async def doit():\n",
    "    identify = random.randint(1, 100)\n",
    "    future = pool.submit(return_after_5_secs, (f\"result: {identify}\"))\n",
    "    awaitable = asyncio.wrap_future(future)\n",
    "    print(f\"waiting result: {identify}\")\n",
    "    return await awaitable\n",
    "\n",
    "\n",
    "async def app():\n",
    "    # run some stuff multiple times\n",
    "    tasks = [doit(), doit()]\n",
    "\n",
    "    result = await asyncio.gather(*tasks)\n",
    "    print(result)\n",
    "\n",
    "print(\"waiting app\")\n",
    "asyncio.run(app())\n",
    "```\n",
    "输出为：\n",
    "```\n",
    "waiting app\n",
    "waiting result: 76\n",
    "waiting result: 87\n",
    "['result: 76', 'result: 87']\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": true,
   "title_cell": "Table of Contents",
   "title_sidebar": "asyncio私房手册",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": true
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
